app/urls.py
from django.urls import path

from app.views import user_views
from app.views import goods_views


app_name = 'app'

urlpatterns = [
    # 注册、登录
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout'),
    path('register/', user_views.register, name='register'),

    path('center/', user_views.center, name='center'),

    path('cart/', goods_views.cart, name='cart'),
    path('add_cart/', goods_views.add_cart, name='add_cart'),
    path('del_cart/', goods_views.del_cart, name='del_cart'),
    path('update_cart/', goods_views.update_cart, name='update_cart'),

    path('order/', user_views.order, name='order'),

    path('buy_now/', goods_views.buy_now, name='buy_now'),
    path('place_order/', goods_views.place_order, name='place_order'),
    path('submit_order/', goods_views.submit_order, name='submit_order'),

    path('site/', user_views.site, name='site'),
    path('update_site/', user_views.update_site, name='update_site'),

    # 首页
    path('index/', goods_views.index, name='index'),
    path('list/', goods_views.list, name='list'),
    path('detail/', goods_views.detail, name='detail'),

]

big_work/urls.py
from django.contrib import admin
from django.urls import include, path
from app.views import goods_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', goods_views.index, name='index'),
    path('app/', include('app.urls')),
]

templates/component/cart_tip.html
<div class="guest_cart fr">
    <a href="{% url 'app:cart' %}" class="cart_name fl">我的购物车</a>
    <div class="goods_count fl" id="show_count">
        {% if request.session.mycart_num %}
            {{ request.session.mycart_num }}
        {% else %}
            0
        {% endif %}
    </div>
</div>

templates/component/foot.html
<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
</div>

templates/component/index_logo.html
<a href="{% url 'app:index' %}" class="logo fl"><img src="/static/images/logo.png" class="logeImageStyle"></a>

templates/component/search_goods.html
<div class="search_con fl">
    <form action="{% url 'app:list' %}" method="get">
        <input type="text" class="input_text fl" name="search_keyword" placeholder="搜索商品" value="{{ search_keyword }}">
        <input type="hidden" name="page_num" value="1">
        <input type="submit" class="input_btn fr" value="搜索">
    </form>
</div>

templates/component/top.html
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到烟火气!</div>
        <div class="fr">

            {% if not request.session.username %}
                <div class="login_btn fl">
                    <a href="{% url 'app:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'app:register' %}">注册</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'app:logout' %}">退出登录</a>
                </div>
            {% endif %}

            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'app:center' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'app:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'app:order' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>