app/urls.py
from django.urls import path

from app.views import user_views
from app.views import goods_views


app_name = 'app'

urlpatterns = [
    # 注册、登录
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout'),
    path('register/', user_views.register, name='register'),

    path('center/', user_views.center, name='center'),

    path('cart/', goods_views.cart, name='cart'),
    path('add_cart/', goods_views.add_cart, name='add_cart'),
    path('del_cart/', goods_views.del_cart, name='del_cart'),
    path('update_cart/', goods_views.update_cart, name='update_cart'),

    path('order/', user_views.order, name='order'),

    path('buy_now/', goods_views.buy_now, name='buy_now'),
    path('place_order/', goods_views.place_order, name='place_order'),
    path('submit_order/', goods_views.submit_order, name='submit_order'),

    path('site/', user_views.site, name='site'),
    path('update_site/', user_views.update_site, name='update_site'),

    # 首页
    path('index/', goods_views.index, name='index'),
    path('list/', goods_views.list, name='list'),
    path('detail/', goods_views.detail, name='detail'),

]

big_work/urls.py
from django.contrib import admin
from django.urls import include, path
from app.views import goods_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', goods_views.index, name='index'),
    path('app/', include('app.urls')),
]

templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>欢迎来到烟火气-购物车</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>

{% include "component/top.html" %}

<div class="search_bar clearfix">
    {% include "component/index_logo.html" %}
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
    {% include "component/search_goods.html" %}
</div>

<div class="total_count">全部商品<em>{{ goods_total_num }}</em>件</div>
<ul class="cart_list_th clearfix">
    <li class="col01">商品名称</li>
    <li class="col02">商品单位</li>
    <li class="col03">商品价格</li>
    <li class="col04">数量</li>
    <li class="col05">小计</li>
    <li class="col06">操作</li>
</ul>

{% for goods_info in goods_list %}
    <ul class="cart_list_td clearfix">
{#        <li class="col01"><input type="checkbox" name="cart_goods_id" checked></li>#}
        <li class="col01"></li>
        <li class="col02"><img src="/static/images/{{ goods_info.pic }}"></li>
        <li class="col03">{{ goods_info.name }}<br><em>{{ goods_info.price }}元/{{ goods_info.unit }}</em></li>
        <li class="col04">{{ goods_info.unit }}</li>
        <li class="col05">{{ goods_info.price }}元</li>
        <li class="col06">
            <div class="num_add">
                <a href="#" class="add fl" onclick="changeBuyNum(1, {{ goods_info.id }})">+</a>
                <input type="text" class="num_show fl" id="cartFormBuyNum{{ goods_info.id }}"
                       value="{{ goods_info.buy_num }}" onchange="onChangeBuyNum({{ goods_info.id }})">
                <a href="#" class="minus fl" onclick="changeBuyNum(-1, {{ goods_info.id }})" >-</a>
            </div>
        </li>
        <li class="col07">{{ goods_info.total_amount }}元</li>
        <li class="col08"><a href="{% url 'app:del_cart' %}?gid={{ goods_info.id }}">删除</a></li>
    </ul>
{% endfor %}

<!-- 修改购物车商品数量 -->
<div style="display: none">
     <form name="updateCartForm" action="{% url 'app:update_cart' %}" method="post" >
        <input type="hidden" name="gid" id="id_card_gid" />
        <input type="hidden" name="gcount" id="id_cart_gcount" />
    </form>
</div>

<ul class="settlements">
{#    <li class="col01"><input type="checkbox" name="" checked=""></li>#}
{#    <li class="col02">全选</li>#}
    <li class="col01"></li>
    <li class="col02"></li>
    <li class="col03">合计(不含运费)：<span>¥</span><em>{{ goods_total_amount }}</em><br>共计<b>{{ goods_total_num }}</b>件商品</li>
    <li class="col04"><a href="{% url 'app:place_order' %}">去结算</a></li>
</ul>

{% include "component/foot.html" %}

<script type="text/javascript">
    function changeBuyNum(num, goods_id) {
        var buyNumObj = document.getElementById("cartFormBuyNum"+goods_id);
        var curNum = buyNumObj.value;
        if (curNum != "") {
            curNum = parseInt(curNum);
        } else {
            curNum = 1;
        }
        curNum = curNum + num;
        if (curNum <= 0) {
            curNum = 1;
        }
        buyNumObj.value = curNum + "";

        // 通知修改
        onChangeBuyNum(goods_id);
    }

    function onChangeBuyNum(goods_id) {
        var buyNum = document.getElementById("cartFormBuyNum"+goods_id).value;
        console.log("===变了", goods_id, buyNum)

        document.getElementById("id_card_gid").value = goods_id;
        document.getElementById("id_cart_gcount").value = buyNum;
        document.updateCartForm.submit();
    }

</script>

</body>
</html>

templates/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>烟火气-商品详情</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">

</head>
<body>

{% include "component/top.html" %}

<div class="search_bar clearfix">
    {% include "component/index_logo.html" %}
    {% include "component/search_goods.html" %}
    {% include "component/cart_tip.html" %}
</div>

<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for goods_type in goods_type_list %}
                    <li><a href="{% url 'app:list' %}?type={{ goods_type.0 }}">{{ goods_type.1 }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">掌上便民</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="breadcrumb">
    <a href="#">全部分类</a>
    <span>></span>
    <a href="#">{{ goods_type_name }}</a>
    <span>></span>
    <a href="#">商品详情</a>
</div>

<div class="goods_detail_con clearfix">
    <div class="goods_detail_pic fl"><img src="/static/images/{{ goods_info.pic }}"></div>

    <div class="goods_detail_list fr">
        <h3>{{ goods_info.name }}</h3>
        <p>{{ goods_info.title }}</p>
        <div class="prize_bar">
            <span class="show_pirze">¥<em>{{ goods_info.price }}</em></span>
            <span class="show_unit">单  位：{{ goods_info.unit }}</span>
        </div>
        <div class="goods_num clearfix">
            <div class="num_name fl">数 量：</div>
            <div class="num_add fl">
                <input type="text" class="num_show fl" name="buyCount" id="idBuyCount" value="1" onchange="onChangeBuyNum({{ goods_info.price }})">
                <a href="#" onclick="changeBuyNum(1, {{ goods_info.price }})" class="add fr">+</a>
                <a href="#" onclick="changeBuyNum(-1, {{ goods_info.price }})" class="minus fr">-</a>
            </div>
        </div>
        <div class="total">总价：<span id="idTotalAmount">{{ goods_info.price }}</span>元</div>
        <div class="operate_btn">
            <a href="#" onclick="validBuyNow()" class="buy_btn">立即购买</a>
            <a href="#" onclick="validAddCart()" class="add_cart" id="add_cart">加入购物车</a>
        </div>

        <div style="display: none">
            <!--立即购买表单-->
            <form name="buyNowForm" action="{% url 'app:buy_now' %}" method="post" >
                <input type="hidden" name="gid" value="{{ goods_info.id }}" />
                <input type="hidden" name="gcount" id="edit_gcount" />
            </form>

            <!--加入购物车表单-->
            <form name="addCartForm" action="{% url 'app:add_cart' %}" method="post" >
                <input type="hidden" name="gid" value="{{ goods_info.id }}" />
                <input type="hidden" name="gcount" id="cart_gcount" />
            </form>
        </div>
    </div>
</div>

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>新品推荐</h3>
            <ul>
                {% for new_goods in new_goods_list %}
                    <li>
                        <a href="{% url 'app:detail' %}?gid={{ new_goods.id }}"><img
                                src="/static/images/{{ new_goods.pic }}"></a>
                        <h4><a href="{% url 'app:detail' %}?gid={{ new_goods.id }}">{{ new_goods.name }}</a></h4>
                        <div class="prize">￥{{ new_goods.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="r_wrap fr clearfix">
        <ul class="detail_tab clearfix">
            <li class="active">商品介绍</li>
            <li>评论</li>
        </ul>

        <div class="tab_content">
            <dl>
                <dt>商品详情：</dt>
                <dd>{{ goods_info.detail }}</dd>
            </dl>
        </div>

    </div>
</div>

{% include "component/foot.html" %}

<div class="add_jump"></div>

<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
<script type="text/javascript">
    var $add_x = $('#add_cart').offset().top;
    var $add_y = $('#add_cart').offset().left;

    var $to_x = $('#show_count').offset().top;
    var $to_y = $('#show_count').offset().left;

    $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})

    function changeBuyNum(num, price) {
        var buyNumObj = document.getElementById("idBuyCount");
        var curNum = buyNumObj.value;
        if (curNum != "") {
            curNum = parseInt(curNum);
        } else {
            curNum = 1;
        }
        curNum = curNum + num;
        if (curNum <= 0) {
            curNum = 1;
        }
        buyNumObj.value = curNum + "";

        onChangeBuyNum(price);
    }

    function onChangeBuyNum(price) {
        var curNum = document.getElementById("idBuyCount").value;
        var totalAmount = price * parseInt(curNum);
         document.getElementById("idTotalAmount").innerText = totalAmount.toFixed(2);
    }

    function validBuyNow() {
        document.getElementById("edit_gcount").value = document.getElementById("idBuyCount").value;
        document.buyNowForm.submit();
    }

    function validAddCart() {
        document.getElementById("cart_gcount").value = document.getElementById("idBuyCount").value;
        document.addCartForm.submit();
    }

</script>

</body>
</html>

templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>烟火气-首页</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
</head>
<body>

{% include "component/top.html" %}

<div class="search_bar clearfix">
    {% include "component/index_logo.html" %}
    {% include "component/search_goods.html" %}

    {% include "component/cart_tip.html" %}

</div>

<div class="navbar_con">
    <div class="navbar">
        <h1 class="fl">全部商品分类</h1>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">掌上便民</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="center_con clearfix">
    <ul class="subnav fl">
        {% for goods_type in goods_type_list %}
            <li><a href="{% url 'app:list' %}?type={{ goods_type.0 }}">{{ goods_type.1 }}</a></li>
        {% endfor %}
    </ul>
    <div class="slide fl">
        <ul class="slide_pics">
            <li><a href="#"><img src="/static/images/banner01.png" alt="幻灯片"></a></li>
            <li><a href="#"><img src="/static/images/banner02.png" alt="幻灯片"></a></li>
            <li><a href="#"><img src="/static/images/banner03.png" alt="猪肉羊肉"></a></li>
            <li><a href="#"><img src="/static/images/banner04.png" alt="新鲜水果"></a></li>
            <li><a href="#"><img src="/static/images/banner05.png" alt="新鲜水果"></a></li>
        </ul>
        <div class="prev"></div>
        <div class="next"></div>
        <ul class="points"></ul>
    </div>
    <div class="adv fl">
        <a href="#"><img src="/static/images/banner01.jpg"></a>
        <a href="#"><img src="/static/images/banner02.jpg"></a>
    </div>
</div>

{% for goods in home_goods_list %}
    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="{{ goods.goods_type_id }}">{{ goods.goods_type_name }}</h3>
            <div class="subtitle fl">
                <span>|</span>
                <a href="#">鲜芒</a>
                <a href="#">加州提子</a>
                <a href="#">亚马逊牛油果</a>
            </div>
            <a href="{% url 'app:list' %}?type={{ goods.goods_type_id }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
        </div>

        <div class="goods_con clearfix">
            <div class="goods_banner fl"><img src="/static/images/{{ goods.goods_type_id }}.jpg"></div>
            <ul class="goods_list fl">
                {% for goods_info in goods.goods_list %}
                    <li>
                        <h4><a href="{% url 'app:detail' %}?gid={{ goods_info.id }}">{{ goods_info.name }}</a></h4>
                        <a href="{% url 'app:detail' %}?gid={{ goods_info.id }}"><img
                                src="/static/images/{{ goods_info.pic }}"/></a>
                        <div class="prize">¥ {{ goods_info.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endfor %}

{% include "component/foot.html" %}

<script type="text/javascript" src="/static/js/slide.js"></script>
{#	<script type="text/javascript">#}
{#		BCSlideshow('focuspic');#}
{#		var oFruit = document.getElementById('fruit_more');#}
{#		var oShownum = document.getElementById('show_count');#}
{##}
{#		var hasorder = localStorage.getItem('order_finish');#}
{##}
{#		if(hasorder)#}
{#		{#}
{#			oShownum.innerHTML = '2';#}
{#		}#}
{##}
{#		oFruit.onclick = function(){#}
{#			window.location.href = 'list.html';#}
{#		}#}
{#	</script>#}
</body>
</html>

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>烟火气-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'app:index' %}" class="login_logo"><img src="/static/images/logo02.png"class="logeImageStyle"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'app:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'app:login' %}" method="post">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">{{ username_error }}</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">{{ password_error }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

    {% include "component/foot.html" %}
	
</body>
</html>

templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>烟火气-注册</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a href="{% url 'app:index' %}" class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'app:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'app:register' %}" method="post">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="username" value="{{ username }}" />
						<span class="error_tip">{{ username_error }}</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="password" id="password">
						<span class="error_tip">{{ password_error }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="samepwd" id="samepwd">
						<span class="error_tip">{{ samepwd_error }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">{{ email_error }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”烟火气用户使用协议“</label>
						<span class="error_tip2"></span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>
		</div>
	</div>

    {% include "component/foot.html" %}
	
</body>
</html>

templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>烟火气-用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>

{% include "component/top.html" %}

<div class="search_bar clearfix">
    {% include "component/index_logo.html" %}
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    {% include "component/search_goods.html" %}
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'app:center' %}" class="active">· 个人信息</a></li>
            <li><a href="{% url 'app:order' %}">· 全部订单</a></li>
            <li><a href="{% url 'app:site' %}">· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user_info.username }}</li>
                <li><span>联系方式：</span>{{ user_info.phone }}</li>
                <li><span>联系地址：</span>{{ user_info.addr }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods_info in goods_list %}
                <li>
                    <a href="{% url 'app:detail' %}?gid={{ goods_info.id }}"><img src="/static/images/{{ goods_info.pic }}" /></a>
                    <h4><a href="{% url 'app:detail' %}?gid={{ goods_info.id }}">{{ goods_info.name }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{ goods_info.price }}</span>
                        <span class="unit">{{ goods_info.price }}/{{ goods_info.unit }}</span>
{#                        <a href="#" class="add_goods" title="加入购物车"></a>#}
                    </div>
                </li>
                {% endfor %}

            </ul>
        </div>
    </div>
</div>


{% include "component/foot.html" %}

</body>
</html>s

templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>烟火气-用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>

{% include "component/top.html" %}

<div class="search_bar clearfix">
    {% include "component/index_logo.html" %}
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
   {% include "component/search_goods.html" %}
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'app:center' %}">· 个人信息</a></li>
            <li><a href="{% url 'app:order' %}" class="active">· 全部订单</a></li>
            <li><a href="{% url 'app:site' %}">· 收货地址</a></li>
        </ul>
    </div>

    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>

        {% for order in user_order_list %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_no }}</li>
                <li class="col02 stress">{{ order.pay_status_desc }} | {{ order.pay_mode_desc }}</li>
            </ul>

            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="55%">
                        {% for detail in order.order_detail_list %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="/static/images/{{ detail.goods_pic }}"></li>
                                <li class="col02">{{ detail.goods_name }}<em>{{ detail.goods_price }}元/{{ detail.goods_unic }}</em>
                                </li>
                                <li class="col03">{{ detail.goods_buy_num }}</li>
                                <li class="col04">{{ detail.goods_amount }}元</li>
                            </ul>
                        {% endfor %}
                    </td>
                    <td width="15%">{{ order.pay_amount }}元</td>
                    <td width="15%">{{ order.pay_status_desc }}</td>
                    <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                </tr>
                </tbody>
            </table>

        {% endfor %}

        <div class="pagenation">
            <a href="#">
                <上一页
            </a>
            <a href="#" class="active">1</a>
            <a href="#">2</a>
            <a href="#">3</a>
            <a href="#">4</a>
            <a href="#">5</a>
            <a href="#">下一页></a>
        </div>
    </div>
</div>

{% include "component/foot.html" %}

</body>
</html>

templates/user_center_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>烟火气-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>

	{% include "component/top.html" %}

	<div class="search_bar clearfix">
		{% include "component/index_logo.html" %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		{% include "component/search_goods.html" %}
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url 'app:center' %}" >· 个人信息</a></li>
				<li><a href="{% url 'app:order' %}" >· 全部订单</a></li>
				<li><a href="{% url 'app:site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>收件人：{{ addr_info.receive_name }}， 手机号码：{{ addr_info.receive_phone }}， 地址：{{ addr_info.receive_addr }}， 邮编：{{ addr_info.postcode }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'app:update_site' %}" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receive_name" id="receive_name" maxlength="20" value="{{ edit_form.receive_name }}">
                            <span class="error_tip">{{ edit_form.receive_name_error }}</span>
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="receive_addr" id="receive_addr">{{ edit_form.receive_addr }}</textarea>
                            <span class="error_tip">{{ edit_form.receive_addr_error }}</span>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" maxlength="6" id="postcode" value="{{ edit_form.postcode }}">
                            <span class="error_tip">{{ edit_form.postcode_error }}</span>
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="receive_phone" maxlength="11" id="receive_phone" value="{{ edit_form.receive_phone }}">
                            <span class="error_tip">{{ edit_form.receive_phone_error }}</span>
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

    {% include "component/foot.html" %}
	
</body>
</html>